### ISSUE TITLE
No way to add storage location on initial setup

### ISSUE THREAD

**Issue by kinghrothgar** [cloudback/issue-tracker#10]
**Is your feature request related to a problem? Please describe.**
I want to use a GCS bucket as my storage location. On setting up my org with hundreds of repositories, there is no way to select another storage option has it hasn't been created yet. After I'm in the main interface, I can then add a new storage option. However, to get this to apply to the hundreds of already enabled repos I'd have to manually edit each one by hand.

**Describe the solution you'd like**
A way to change the storage location for all enabled repos

**Comment by arxange1** [comment]
Dear @kinghrothgar, 

Thank you for reaching out!

## Proposed solution 

Implement bulk operations for account repositories. Operations to be implemented:
 - enable/disable scheduled backups
 - change storage
 - change schedule

**Comment by SeanDeen** [comment]
## Proposed UI of `Bulk Operations` dialog

![image](https://user-images.githubusercontent.com/26085217/122825372-832ee180-d2ea-11eb-9a86-c1c88eea23ac.png)
