### ISSUE TITLE
Slack notification integration

### ISSUE THREAD

**Issue by fsz-codeshop** [cloudback/issue-tracker#11]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have no visibility of third party service tools. I don't feel like entering their web interface to check the status of the scheduled jobs.

**Describe the solution you'd like**
I would like to receive a slack message on my DevOps team channel with the result of the github backup status (successes/failures) so that I can know if my backups are indeed working and quickly work on failed ones.

**Describe alternatives you've considered**
Log in everyday into the web interface to check status and/or check email notification for failures.

**Additional context**
Example:
![feature_request](https://user-images.githubusercontent.com/79223916/153212739-dbe51eef-d5ec-423e-a08c-82ea3b9842ce.jpg)

**Comment by arxange1** [comment]
Hi @fsz-codeshop, sorry for the delay. Thank you for the feature suggestion! The feature sounds really useful and we will take it into development. We will keep you updated on the progress.

**Comment by arxange1** [comment]
Hi @fsz-codeshop, we released the feature, please check if it works for you.
![instant-notifications](https://user-images.githubusercontent.com/2320016/170828202-52f4916e-1753-4642-9969-8f7f013412a9.gif)
