### ISSUE TITLE
Backup Password Emails

### ISSUE THREAD

**Issue by owenparry-pb** [cloudback/issue-tracker#14]
I selected a backup to download from the portal to test opening it. The first backup I downloaded, I received the password immediately. 

![image](https://user-images.githubusercontent.com/73891819/194905522-cb0880a9-e1c6-4104-984f-b9a2f91bdebb.png)

Because that was stored on your Storage (my initial backups) - I wanted to test it on my S3 bucket. I downloaded today's from the same repository - but never received the email containing the password.  (The one with an X)

I have now attempted to download other repositories as tests in the AutoElevate Respoitorty, and I'm not getting any emails.

The emails are not located in my spam filter.

**Comment by arxange1** [comment]
@owenparry-pb I removed your email from the unsubscribe group, could you please download an archive again in order to get a password?
