### ISSUE TITLE
We selected a schedule of daily at 8pm s and yet for all of our repos the schedule says daily at 6am. We even tried to do a bulk operation to update it and it didn't work. Any advice? 

### ISSUE THREAD

**Issue by demnett22** [cloudback/issue-tracker#16]
We selected a schedule of daily at 8pm s and yet for all of our repos the schedule says daily at 6am. We even tried to do a bulk operation to update it and it didn't work. Any advice?

**Comment by arxange1** [comment]
Dear @demnett22, let us double-check the issue...

**Comment by arxange1** [comment]
Dear @demnett22, 
I am pleased to inform you that the issue you encountered within the `Bulk Operations` dialog, which prevented the application of schedules, has now been resolved. Our team has implemented the fix and it has been deployed in our production environment. You may now attempt the process again, it should work now. Also, please note, for your understanding, that any schedule defined within the `Account Settings` dialog does not apply retroactively to existing repositories. It sets a default schedule for any new repositories created henceforth.

Thank you for telling us about this problem and sorry for any trouble it caused.

Thank you for reporting the bug and sorry for the inconvenience caused.
