### ISSUE TITLE
Cards view (view all) & table view not working

### ISSUE THREAD

**Issue by wh33ler** [cloudback/issue-tracker#17]
**Describe the bug**
View all function n cards view and the complete table view is not working for me

*To Reproduce**
1. Go to 'table view' or click on `view all` in cards view

**Expected behavior**
should work 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser safari

**Additional context**

**Comment by arxange1** [comment]
@wh33ler, could you please check if it works for you now?

**Comment by wh33ler** [comment]
Working again. Thank you for the quick turnaround.
