### ISSUE TITLE
Backup fails with "Limit Exceeded"

### ISSUE THREAD

**Issue by MiKluge** [cloudback/issue-tracker#19]
**Describe the bug**
Whenever I try to back-up my GitHub-Repo I get a "Limit exceeded" error-message

**To Reproduce**
1. Setup a backup for a Github-Repo
2. Trigger the backup
3. Wait for the error-message 

**Expected behavior**
The backup succeeds without an error

**Screenshots**
![image](https://github.com/cloudback/issue-tracker/assets/149514163/6843df60-8e58-445b-9cad-765c00860814)

**Comment by arxange1** [comment]
Dear @MiKluge, 
It is because the ZIP archive size is more than 100MB, which is the size limit for the "Free Plan". Please consider switching to "Per 10 repo" plan or decrease the total size of the repository.

Best regards,
Victor, Cloudback Team

**Comment by MiKluge** [comment]
Hello Victor,
thank you so much for the quick and helpful reply! I was already thinking that there might be a total size limit, but I wasn't able to find any information in the documentation. 
Greetings, 
Michael

**Comment by MiKluge** [comment]
I am stupid - I just saw the size-limit in the "plan description" at the Github-Marketplace....
Sorry for the inconvenience!

**Comment by arxange1** [comment]
I see, documentation issue indeed. The only place it is mentioned is the GitHub Marketplace. We will update the documentation on the website.
