### ISSUE TITLE
AWS S3 object tagging

### ISSUE THREAD

**Issue by m477r1x** [cloudback/issue-tracker#20]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I thought it might be nice if when using S3 storage, when the app performs the `PutObject` action to place the backup zip file, if the object could be tagged with something like `repository=<thing>`.  

**Describe alternatives you've considered**
N/A

**Additional context**
I was chatting with our team this morning and looking at the S3 bucket where our backups are stored and of course all the zip file objects are named with metadata names which I assume are generated within Cloudback. We thought it might be nice to be able to browse to the bucket and at a glance, see which backup is which from a repo perspective in GitHub? Now, of course changing the names of the backup objects I appreciate might be a bit of a larger change within the code base, but adding tags to the objects would at least allow a user to search in the AWS console in S3 and filter by object tag for the name of the GitHub repository which they are looking for the backup for.

The reason we might want to do this, is if the Cloudback console is unavailable for some reason, or if we want to use S3 bucket replication or any other mechanism which might mean we want to check our backup objects at a glance within AWS.

**Comment by arxange1** [comment]
Dear @m477r1x,
There is an in-buit customization of HTTP headers for that purpose. You can add a new [x-amz-tagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) HTTP header into your storage configuration, for example:
```
x-amz-tagging: repository=<thing>
```

The only issue is to get the name of repository that is being processed. We currently doesn't support that. The proposal it to implement it using templating, like in the example below:
```
x-amz-tagging: repository={{ repositoryName }}
```

Screenshot for reference:
![image](https://github.com/cloudback/issue-tracker/assets/2320016/c6693209-805d-4879-9840-4706a5e6370f)

**Comment by m477r1x** [comment]
Amazing! I didn't know about this feature, sorry to have logged a feature request for something which is already implemented 🙂

**Comment by arxange1** [comment]
Yes, you can configure one single storage for all 250 repos, and configure the HTTP header using the placeholder like in the example below:
```
x-amz-tagging: repository={{ repositoryName }}
```

the "{{ repositoryName }}" placeholder will be replaced with the name of repository that is being processed.

But please wait until we implement that placeholder and release it to production.

**Comment by arxange1** [comment]
Dear @m477r1x,

We released it to the production environment. Please try the following format and let us know if it works for you:
```
x-amz-tagging: repository={{ context.RepositoryName }}
```
Reference:
- https://docs.cloudback.it/features/s3-object-tag/

**Comment by arxange1** [comment]
@m477r1x please note, that you need to grant s3:PutObjectTagging permission at a bucket level and at an access point level if you use access points.
