### ISSUE TITLE
Pull request comments contain no original text

### ISSUE THREAD

**Issue by carlsonmark** [cloudback/issue-tracker#22]
**Describe the bug**
When pull request comments are restored, they are restored as a single line with the username but no original comment text.

**To Reproduce**
1. Create a PR in a repository
2. Add a comment to the PR
3. Back up the repository on https://app.cloudback.it
4. Delete the repository
5. Restore the repository (and wait for it to fully finish)
6. View PR in restored repository

**Expected behavior**
The PR had comments in it originally, and I expect that they will be restored when the repository is restored. I know there are API limitations for this, but it seems like there is actually a bug here.

The contents of the PR comments are simply: "<username> wrote at <date>" without any of the original text at all. The `pull-requests.json` file in the backup has the text of the original comment... it is just not restored.

**Screenshots**
Before deleting and restoring the repository:
![image](https://github.com/cloudback/issue-tracker/assets/7170924/02c2b05c-594b-4743-bec3-119d0be4dec4)

After deleting and restoring the repository:
![image](https://github.com/cloudback/issue-tracker/assets/7170924/dcd67c11-c7ef-4751-8802-b63b0a3096a6)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Browser Firefox
 - Version 124.0.2

**Additional context**
I did not check if the initial comment was restored correctly. My test PRs had no text in the main PR comment.

**Comment by arxange1** [comment]
@carlsonmark The fix is done, please check if it works for you.

**Comment by arxange1** [comment]
I see. That's wrong and to be fixed. Let us double check it again.

**Comment by arxange1** [comment]
We were able to reproduce the issue and have implemented a fix. Could you please confirm if the problem has been resolved on your end?

**Comment by carlsonmark** [comment]
Much better now, thanks!
![image](https://github.com/cloudback/issue-tracker/assets/7170924/5aeeb4db-fbd3-4d16-bcab-f3738e6d483c)
