### ISSUE TITLE
Changing the default storage for an account on the Account Settings page fails to save

### ISSUE THREAD

**Issue by mattbilson-hnry** [cloudback/issue-tracker#24]
**Describe the bug**
Changing the default storage for an account on the Account Settings page fails to save

**To Reproduce**
1. Go to the Account Settings page
2. Select an account
3. Select a different storage in the Default Storage dropdown
4. Click Save
5. Refresh page

**Expected behavior**
Expect to see the previously selected storage as the new default storage, but it reverts to the previous default storage

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 14.4 (23E214)
 - Browser - Chrome
 - Version - 123.0.6312.122

**Additional context**
This is on a trial account, in case that makes a difference

**Comment by arxange1** [comment]
Dear @mattbilson-hnry, 

Thank you for letting us know, that bug is fixed, could you please check?
