### ISSUE TITLE
New Storage -> Deduplication Type -> hidden text

### ISSUE THREAD

**Issue by Vetavize-Robert** [cloudback/issue-tracker#27]
**Describe the bug**
When adding new storage, the dropdown under Deduplication type does not display all of the text. (You can read it if you inspect the element, but it is cutoff as a user.  Text is also confusing.

**To Reproduce**
1. Go to https://app.cloudback.it/storages/new
2. Click on Deduplication type
3. Text is cut off

**Expected behavior**
Full text should be visible to the user:

Here is the existing text:
Deduplicate, do not create new ZIP archive if nothing has changed since the last backup
Do not deduplicate, create new ZIP archive always

The text is confusing and not clear as deduplicate is not a common word. May I suggest the following: 
Only Archive if Changes Have Occurred - No Duplicates
Always Archive - Duplicates Allowed

**Screenshots**
![image](https://github.com/cloudback/issue-tracker/assets/169933777/9f8e5d30-1bc9-4360-b6d2-724885daf2e3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by arxange1** [comment]
Dear @Vetavize-Robert, thank you for your feedback, we will improve the wording and will report you back.

**Comment by arxange1** [comment]
The fix is implemented, please check
