### ISSUE TITLE
Cannot Edit S3 Glacier Storage

### ISSUE THREAD

**Issue by Vetavize-Robert** [cloudback/issue-tracker#28]
**Describe the bug**
When I click the edit icon for Amazon S3 Glacier, I get an error.

**To Reproduce**
1. Go to https://app.cloudback.it/storages
2. Click on The Edit button for Amazon S3 Glacier

**Expected behavior**
Editing of the storage.

**Screenshots**

![image](https://github.com/cloudback/issue-tracker/assets/169933777/5c381e7e-50e8-47b8-b72e-aec469557436)

![image](https://github.com/cloudback/issue-tracker/assets/169933777/41b7cdd6-db9e-4b65-911b-e0519e932149)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome
- Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by arxange1** [comment]
Dear @Vetavize-Robert,

We are currently experiencing a partial service downgrade due to recent infrastructure changes. To resolve this issue, we will be shutting down the entire site today. We will notify you as soon as the issue is resolved.

Additionally, you can check the service health reports on the status page:
* https://docs.cloudback.it/status/

**Comment by arxange1** [comment]
Dear @Vetavize-Robert, the maintenance is done. the system is fully operational, please check

**Comment by arxange1** [comment]
The issue with the S3 Glacier Storage Editor is not related to the maintenance; it is a confirmed bug. We are already working on a fix.

**Comment by arxange1** [comment]
The fix is implemented, please check

**Comment by Vetavize-Robert** [comment]
It does not look like it is resolved. 

![image](https://github.com/user-attachments/assets/53a20293-d49d-4b77-8e72-acd16370d88c)

While I understand given that it is S3 Glacier there is no way to make it an instant download, I do not see a path to get a download through your service. Perhaps an email with a link to the download when available or another notification?

**Comment by Vetavize-Robert** [comment]
Editing works well. Thank you for the fix!
