### ISSUE TITLE
My another team mate from same organisation not able to see backups when he login using his github account.

### ISSUE THREAD

**Issue by NitishMehtaEncollab** [cloudback/issue-tracker#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elv1s42** [comment]
Hi @NitishMehtaEncollab,

To address the issue your teammate is experiencing, ensure that they have the "Owner" role within the GitHub organization. Only members with this role can access and configure backups on Cloudback. Additionally, ask them to log in to GitHub and check that the organization is accessible.

If the problem persists, please provide additional details, including the account name that cannot access the backups.

**Comment by arxange1** [comment]
We plan to improve our end-user documentation as a separate project, which will address all raised documentation issues. Since there are no immediate actions required, we are closing this issue for now.
