### ISSUE TITLE
Deduplication over period chart does not show for composite storage. 

### ISSUE THREAD

**Issue by Vetavize-Robert** [cloudback/issue-tracker#31]
**Describe the bug**
When a composite data storage solution is used (Cloudback + s3 glacier) 

**Statistics** show without issue:
![image](https://github.com/user-attachments/assets/0689caf4-c02a-4898-ad1d-5c023a6d699c)

but, **Deduplication over period** does not show
![image](https://github.com/user-attachments/assets/7b79f095-855a-4c39-803e-c7ef40bbee40)

Also you have 30, 60, 90, and 365 days as retention periods, it might be nice to have the same selections for the chart, right now it is last week and last month. Adding last 60, 90, and 365 days might be nice, but not necessary. 

**To Reproduce**
1. Create a composite storage solution
2. Wait for a few backups
3. Go to repository details. 
4. See empty **Deduplication over period**  chart. 

**Expected behavior**
chart populated

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 127.0.6533.89

**Comment by arxange1** [comment]
Dear @Vetavize-Robert,
There haven't been any deduplicated backups since July 22, 2024. The chart is correct but looks empty, which might be confusing. We'll work on making it more user-friendly.

**Comment by Vetavize-Robert** [comment]
That makes sense. This specific repository adds data each day, so there would be no duplicates.

**Comment by elv1s42** [comment]
Dear @Vetavize-Robert,

We've implemented the improvement to cover the cases when the charts are empty:
![image](https://github.com/user-attachments/assets/069a4c62-e205-4ffd-8c51-ae0d3646a8c0)

Also, the new selections for the charts were added:
![image](https://github.com/user-attachments/assets/656d4a25-b34c-4f2f-8bef-79ef87a05f9c)

Thank you for the valuable feedback!

**Comment by Vetavize-Robert** [comment]
That is a great change. It makes it clear and flexible. Thank you for the improvements!
