### ISSUE TITLE
deduplicate history graph

### ISSUE THREAD

**Issue by Vetavize-Robert** [cloudback/issue-tracker#32]
**Describe the bug**
The graph does not appear to have an accurate count

**To Reproduce**
View a graph with deduplicates and non-deduplicates

**Expected behavior**
I would expect the graph to grow evenly. Right now if there is new data it is shown in grey but the next day the total size goes down.

Let's look at Sep 5 and Sep 6 in the screenshot. 

On Sep 5 new data was added. I look at the bar and it looks like the deduplicated size is stacked with the total size. I would expect that the total length of the bar would represent the size. When we look at Sep 6, the size looks like it goes down. I would expect that if we added size on Sep 5, and did not add to size on Sep 6, those two days would have the same height, but Sep 5 would have a section that is grey and Sep 6 would be all green. 

Having the size go down makes it look incorrect. 

**Screenshots**
![image](https://github.com/user-attachments/assets/6b0a95aa-2cb3-46d8-97b7-36169f80b610)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by arxange1** [comment]
Dear @Vetavize-Robert,

Thank you for reporting the issue. It is fixed now, please check.

Best regards,
Victor

**Comment by Vetavize-Robert** [comment]
Looks great! Thank you for the fix.
