### ISSUE TITLE
Support for openstack swift

### ISSUE THREAD

**Issue by manuvakery1** [cloudback/issue-tracker#6]
**Is your feature request related to a problem? Please describe.**
It would be nice to add support for openstack swift as well

**Describe the solution you'd like**
I should be able to backup my github repositories to openstack swift/ s3 compatible storage

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by arxange1** [comment]
## Proposed Solution

Support storages based on **S3 API** with **Account Key** authorization. It should cover the majority of S3 API compatible providers, including but not limited to **OpenStack Swift**

## References

- https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html#s3cmd

**Comment by manuvakery1** [comment]
> ## Proposed Solution
> Support storages based on **S3 API** with **Account Key** authorization. It should cover the majority of S3 API compatible providers, including but not limited to **OpenStack Swift**.
> 
> ## References
> * https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html#s3cmd

Great, makes perfect sense

**Comment by manuvakery1** [comment]
@arxange1 I have tested it and working well. Not all swift deployment has s3api enabled(its an optional feature in swift). The storage provider name can be changed to something specific to S3 compatible storage

**Comment by Stevielocs** [comment]
I am linked to someone else account need to unlink
