### ISSUE TITLE
Error occurred: RequestID: 0HM8M9N4DBI3I:00000001

### ISSUE THREAD

**Issue by fkali** [cloudback/issue-tracker#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arxange1** [comment]
Steps to reproduce:

1. Create a repository
2. Create a backup for the repository 
3. Delete repository 
4. Dashboard crashes

**Comment by arxange1** [comment]
@fkali, The bug was introduced by the recent enhancement of organization account handling. Now it is localized and fixed. Please check.
