### ISSUE TITLE
Support ignoring archived repositories

### ISSUE THREAD

**Issue by kinghrothgar** [cloudback/issue-tracker#9]
**Is your feature request related to a problem? Please describe.**
I would like to automatically backup all non-archived repositories for an organization. I am looking to onboard all of my companies organization's hundreds of repositories. However, I do not want to backup archived repositories. Currently it appears I would have to manually go through and find and disable the 70 something out of 400 repositories that are archived after selecting "enable all" on initial setup.

Also, once a repository is archived, I no longer what new backups to be taken as there is no reason to have scheduled backups for a read-only repo.

**Describe the solution you'd like**
Add option to enable backups for all non-archived repositories
Add option to disable backups for repositories that have been archived.

**Comment by elv1s42** [comment]
Dear @kinghrothgar, 

Thank you for reaching out!

## Proposed solution 

Implement filters to select multiple repositories based on:
 - repository owner
 - repository visibility (public or private)
 - repository status (active or archived)

Implement bulk operations for selected repositories. Operations to be implemented:
 - enable/disable scheduled backups
 - change backup storage
 - change schedule

As far as I understand, this implementation will partially cover issue #10, as you will be able to modify storage for multiple repositories after the initial setup is completed.

Please let us know if the proposed solution will work for you.

**Comment by SeanDeen** [comment]
## Proposed UI for `Account Settings` dialog

![image](https://user-images.githubusercontent.com/26085217/122825591-d0ab4e80-d2ea-11eb-8761-ebc86e366828.png)
